apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "kubelive1"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "kubelive1"
    spec:
      containers:
        - name: "kubelive1"
          image: "jwtoauth20200502074242.azurecr.io/kubelive1"
          ports:
          - containerPort: 80